name: Feature Request
description: Suggest a new feature to be added to BeagleEditor in the future
title: "Feature Request: "
labels: [enhancement, new-feature]
body:
  - type: markdown
    attributes:
      value: |
        **IMPORTANT:** Don't post off-topic comments.
        Please don't ask your questions here. Any questions will be closed.
  - type: checkboxes
    attributes:
      label: Please check these checkboxes, if you already did them
      description: These are required for opening an issue
      options:
        - label: I have searched for [existing issues](https://github.com/beaglesoftware/editor)
          required: true
        - label: I have installed latest version of BeagleEditor (and plugins)
          required: true
  - type: input
    attributes:
      label: Write a summary of what you like to be added in the future
      placeholder: for example, I like to add a new cool feature called AI chat
    validations:
      required: true
  - type: textarea
    attributes:
      label: Describe your feature request
      description: A clear and concise description of what does it do and more details. 
    validations:
      required: false
  - type: checkboxes
    options:
      - label: I have checked that the feature already exists or not
        required: true
  - type: markdown
    attributes:
      value: |
        Again! **NO OFF-TOPIC COMMENTS. UNLESS YOU WILL BE BLOCKED**
        We only allow good manners
        If you have any questions, ask them in [Discussions](https://github.com/beaglesoftware/editor/discussions)
        
        We wish you the best,
        BeagleSoftware
        
