name: Feature Request
description: Suggest a new feature to be added to BeagleEditor in the future
title: "Feature Request: "
label: [enhancement, new-feature]
body:
  - type: markdown
    attributes:
      value: |
        **IMPORTANT:** Don't post off-topic comments.
        Please don't ask your questions here. Any questions that are off-topic, will be closed
  - type: checkbox
    attributes:
      - label: I have searched for [existing issues](https://github.com/beaglesoftware/editor)
        required: true
      - label: I have installed latest version of BeagleEditor (and plugins)
        required: true
  - type: input
    attributes:
      label: Write a summary of what you like to be added in the future
      placeholder: for example, I like to add a new cool feature called AI chat
    validation:
      required: true
  - type: textarea
    attributes:
      label: Describe your feature request
      description: A clear and concise description of what does it do and more details. 
    validation:
    required: false
  - type: checkbox
    attributes:
      label: I have checked that the feature already exists or not
  - type: markdown
    attributes:
      value: |
        Again! **NO OFF-TOPIC COMMENTS. UNLESS YOU WILL BE BLOCKED**
        We only allow good manners
        If you have any questions, ask them in [Discussions](https://github.com/beaglesoftware/editor/discussions)
        
        We wish you the best,
        BeagleSoftware
        
